In [38]:
import pandas as pd 
import numpy as np
import matplotlib as plt 
import seaborn as sns

In [39]:
clientes = pd.read_excel('../clean_data/clientes.xlsx')
detalle_ventas = pd.read_excel('../clean_data/detalles_ventas_clean.xlsx')
productos = pd.read_excel('../clean_data/productos_clean.xlsx')
ventas = pd.read_excel('../clean_data/ventas_clean.xlsx')

df_list = [clientes, detalle_ventas, productos, ventas]

In [40]:
name_list = ["clientes", "detalle_ventas", "productos", "ventas"]

for i, tabla in enumerate(df_list):
    print(f'=========== {name_list[i].upper()} ============')
    display(tabla.info())
    display(tabla.describe())

=========== CLIENTES ============
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_cliente      100 non-null    int64
 1   nombre_cliente  100 non-null    object
 2   email           100 non-null    object
 3   ciudad          100 non-null    object
 4   fecha_alta      100 non-null    datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(3)
memory usage: 4.0+ KB

None

       id_cliente           fecha_alta
count  100.000000                  100
mean    50.500000  2023-02-19 12:00:00
min      1.000000  2023-01-01 00:00:00
25%     25.750000  2023-01-25 18:00:00
50%     50.500000  2023-02-19 12:00:00
75%     75.250000  2023-03-16 06:00:00
max    100.000000  2023-04-10 00:00:00
std     29.011492                  NaN

=========== DETALLE_VENTAS ============
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 343 entries, 0 to 342
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_venta         343 non-null    int64
 1   id_producto      343 non-null    int64
 2   nombre_producto  343 non-null    object
 3   cantidad         343 non-null    int64
 4   precio_unitario  343 non-null    int64
 5   importe          343 non-null    int64
dtypes: int64(5), object(1)
memory usage: 16.2+ KB

None

         id_venta  id_producto    cantidad  precio_unitario       importe
count  343.000000   343.000000  343.000000       343.000000    343.000000
mean    61.492711    49.139942    2.962099      2654.495627   7730.078717
std     34.835525    29.135461    1.366375      1308.694720   5265.543077
min      1.000000     1.000000    1.000000       272.000000    272.000000
25%     31.000000    23.000000    2.000000      1618.500000   3489.000000
50%     61.000000    47.000000    3.000000      2512.000000   6702.000000
75%     93.000000    76.000000    4.000000      3876.000000  10231.500000
max    120.000000   100.000000    5.000000      4982.000000  24865.000000

=========== PRODUCTOS ============
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_producto      100 non-null    int64
 1   nombre_producto  100 non-null    object
 2   categoria        100 non-null    object
 3   precio_unitario  100 non-null    int64
dtypes: int64(2), object(2)
memory usage: 3.2+ KB

None

       id_producto  precio_unitario
count   100.000000       100.000000
mean     50.500000      2718.550000
std      29.011492      1381.635324
min       1.000000       272.000000
25%      25.750000      1590.000000
50%      50.500000      2516.000000
75%      75.250000      4026.500000
max     100.000000      4982.000000

=========== VENTAS ============
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_venta        120 non-null    int64
 1   fecha           120 non-null    datetime64[ns]
 2   id_cliente      120 non-null    int64
 3   nombre_cliente  120 non-null    object
 4   email           120 non-null    object
 5   medio_pago      120 non-null    object
dtypes: datetime64[ns](1), int64(2), object(3)
memory usage: 5.8+ KB

None

         id_venta                fecha  id_cliente
count  120.000000                  120  120.000000
mean    60.500000  2024-03-29 17:36:00   47.291667
min      1.000000  2024-01-02 00:00:00    1.000000
25%     30.750000  2024-02-11 06:00:00   24.500000
50%     60.500000  2024-03-25 00:00:00   48.500000
75%     90.250000  2024-05-19 06:00:00   67.500000
max    120.000000  2024-06-28 00:00:00  100.000000
std     34.785054                  NaN   27.854181

## Observaciones 
- Hacer un merge de todas las tablas 
- Eliminar columnas duplicadas 
- Convertir los tipos de datos (preprocesamiento de datos)
- Crear nuevas columnas (mes, anio, dia de la semana)
- Graficar usando mpl
- Graficar usando sns

## Cosas a tener en cuenta para la demo
- Usar heatmap para analisis de correlaciones
- El programa en python muestra la documentacion actualizada

In [43]:
df_venta_cliente = ventas.merge(clientes[['ciudad', 'id_cliente']], on='id_cliente' , how='left')
df_todos = detalle_ventas.merge(df_venta_cliente[["fecha","medio_pago","id_venta"]], on='id_venta', how='left').merge(productos, on='id_producto', how='left')

display(df_todos.describe())
display(df_todos.columns)
display(df_todos.head())

,id_venta,id_producto,cantidad,precio_unitario_x,importe,fecha,precio_unitario_y
count,343.000000,343.000000,343.000000,343.000000,343.000000,343,343.000000
mean,61.492711,49.139942,2.962099,2654.495627,7730.078717,2024-03-30 14:12:14.693877504,2654.495627
min,1.000000,1.000000,1.000000,272.000000,272.000000,2024-01-02 00:00:00,272.000000
25%,31.000000,23.000000,2.000000,1618.500000,3489.000000,2024-02-10 12:00:00,1618.500000
50%,61.000000,47.000000,3.000000,2512.000000,6702.000000,2024-03-26 00:00:00,2512.000000
75%,93.000000,76.000000,4.000000,3876.000000,10231.500000,2024-05-21 00:00:00,3876.000000
max,120.000000,100.000000,5.000000,4982.000000,24865.000000,2024-06-28 00:00:00,4982.000000
std,34.835525,29.135461,1.366375,1308.694720,5265.543077,NaN,1308.694720

Index(['id_venta', 'id_producto', 'nombre_producto_x', 'cantidad',
       'precio_unitario_x', 'importe', 'fecha', 'medio_pago',
       'nombre_producto_y', 'categoria', 'precio_unitario_y'],
      dtype='object')

,id_venta,id_producto,nombre_producto_x,cantidad,precio_unitario_x,importe,fecha,medio_pago,nombre_producto_y,categoria,precio_unitario_y
0,1,90,TOALLAS HÚMEDAS X50,1,2902,2902,2024-06-19,TARJETA,TOALLAS HÚMEDAS X50,LIMPIEZA,2902
1,2,82,ACEITUNAS NEGRAS 200G,5,2394,11970,2024-03-17,QR,ACEITUNAS NEGRAS 200G,LIMPIEZA,2394
2,2,39,HELADO VAINILLA 1L,5,469,2345,2024-03-17,QR,HELADO VAINILLA 1L,ALIMENTOS,469
3,2,70,FERNET 750ML,2,4061,8122,2024-03-17,QR,FERNET 750ML,LIMPIEZA,4061
4,2,22,MEDIALUNAS DE MANTECA,1,2069,2069,2024-03-17,QR,MEDIALUNAS DE MANTECA,LIMPIEZA,2069

Todos id's, emails, nombre cliente,

In [51]:
df = df_todos

df = df.drop(columns=['id_venta','id_producto','nombre_producto_x','precio_unitario_x'])
df.rename(columns={'nombre_producto_y':'producto','precio_unitario_y':'precio','importe':'total'}, inplace=True)

df = df[['producto','categoria','cantidad','precio','total','medio_pago','fecha']]
display(df.tail())

,producto,categoria,cantidad,precio,total,medio_pago,fecha
338,FERNET 750ML,LIMPIEZA,2,4061,8122,EFECTIVO,2024-02-09
339,CEPILLO DE DIENTES,ALIMENTOS,3,2142,6426,EFECTIVO,2024-02-09
340,AZÚCAR 1KG,LIMPIEZA,2,727,1454,EFECTIVO,2024-02-09
341,FIDEOS SPAGHETTI 500G,ALIMENTOS,5,745,3725,QR,2024-02-07
342,PAN LACTAL BLANCO,LIMPIEZA,5,1571,7855,TARJETA,2024-04-21

In [56]:
#Transformar datos
medios = {"EFECTIVO": 0 , "TARJETA": 1, "QR":2, "TRANSFERENCIA": 3}

df["medio_pago"] = df["medio_pago"].replace(medios)

display(df.tail())
display(df.sample(20))

/tmp/ipykernel_42812/818493212.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["medio_pago"] = df["medio_pago"].replace(medios)

,producto,categoria,cantidad,precio,total,medio_pago,fecha
338,FERNET 750ML,LIMPIEZA,2,4061,8122,0,2024-02-09
339,CEPILLO DE DIENTES,ALIMENTOS,3,2142,6426,0,2024-02-09
340,AZÚCAR 1KG,LIMPIEZA,2,727,1454,0,2024-02-09
341,FIDEOS SPAGHETTI 500G,ALIMENTOS,5,745,3725,2,2024-02-07
342,PAN LACTAL BLANCO,LIMPIEZA,5,1571,7855,1,2024-04-21

,producto,categoria,cantidad,precio,total,medio_pago,fecha
257,CERVEZA NEGRA 1L,LIMPIEZA,3,1533,4599,0,2024-01-29
151,QUESO RALLADO 150G,LIMPIEZA,2,3444,6888,1,2024-03-26
239,CHOCOLATE AMARGO 100G,LIMPIEZA,4,2234,8936,3,2024-01-23
54,PIZZA CONGELADA MUZZARELLA,LIMPIEZA,5,4286,21430,3,2024-06-19
336,VINO BLANCO 750ML,LIMPIEZA,5,2684,13420,0,2024-02-09
157,ACEITE DE GIRASOL 1L,ALIMENTOS,4,860,3440,0,2024-01-10
50,MERMELADA DE FRUTILLA 400G,LIMPIEZA,2,1584,3168,0,2024-06-11
53,CHOCOLATE AMARGO 100G,LIMPIEZA,3,2234,6702,1,2024-01-13
228,YERBA MATE INTENSA 1KG,LIMPIEZA,2,4883,9766,3,2024-03-09
180,ACEITE DE GIRASOL 1L,ALIMENTOS,2,860,1720,2,2024-03-07
96,CHOCOLATE AMARGO 100G,LIMPIEZA,5,2234,11170,3,2024-01-13
299,TÉ NEGRO 20 SAQUITOS,LIMPIEZA,4,570,2280,0,2024-05-21
231,PAPAS FRITAS ONDULADAS 100G,ALIMENTOS,5,1868,9340,1,2024-01-25
193,MERMELADA DE FRUTILLA 400G,LIMPIEZA,3,1584,4752,3,2024-02-02
143,DESODORANTE AEROSOL,ALIMENTOS,4,4690,18760,3,2024-01-09
194,CAFÉ MOLIDO 250G,ALIMENTOS,3,2053,6159,2,2024-06-02
30,PAPEL HIGIÉNICO X4,LIMPIEZA,3,2532,7596,0,2024-06-28
137,QUESO RALLADO 150G,LIMPIEZA,3,3444,10332,0,2024-06-02
146,YERBA MATE SUAVE 1KG,ALIMENTOS,4,3878,15512,1,2024-05-10
95,YERBA MATE INTENSA 1KG,LIMPIEZA,1,4883,4883,3,2024-01-13